import FinancingSection from "@/components/FinancingSection";
// ... existing code ...
export default function FinanciamientoPage() {
  // ... existing code ...
  return (
    <main className="px-4">
      <FinancingSection />
    </main>
  );
  // ... existing code ...
}
// ... existing code ...